using System;
using System.Text;
using System.Globalization;

/// <summary>
/// This class wraps an array of floats and gives its parts 
/// meaningful names along with static and dynamic checks.
/// It also provides a ToString function printing all of the fields.
/// There are two constructors, one wraps existing array
/// and the other is used to create a new one.
/// </summary>
/// <remarks>
/// This file was generated by python script
/// "channel_generator.py" from "VectorAction.ch".
/// Do not edit it directly, instead edit either of them. 
/// </remarks>
public class VectorAction {
	public float[] array {get; private set;}

	public VectorAction(float[] source) {
		if(source.Length!=length){
			throw new ArgumentException("The size of passed array is incorrect");
		}
		array=source;
	}

	public VectorAction() {
		array=new float[length];
	}

	/// <summary>
	/// Takes part of the array starting at start and containing count 
	/// elements and writes its string representation to StringBuilder.
	/// </summary>
	void SliceToString(StringBuilder sb, int start, int count, CultureInfo culture)
    {
        bool first = true;
        for (int i=0; i < count; i++)
        {
            if (!first)
                sb.Append(", ");
            sb.Append(array[start+i].ToString("0.##", culture));
            first = false;
        }
    }

	public float Longitudinal 
	{
		get {
			return array[0];
		}
		set {
			array[0]=value;
		}
	}

	public float Lateral 
	{
		get {
			return array[1];
		}
		set {
			array[1]=value;
		}
	}

	public float Vertical 
	{
		get {
			return array[2];
		}
		set {
			array[2]=value;
		}
	}

	public float Yaw 
	{
		get {
			return array[3];
		}
		set {
			array[3]=value;
		}
	}

	public float Camera 
	{
		get {
			return array[4];
		}
		set {
			array[4]=value;
		}
	}

	public float Grabber 
	{
		get {
			return array[5];
		}
		set {
			array[5]=value;
		}
	}

	public float Torpedo 
	{
		get {
			return array[6];
		}
		set {
			array[6]=value;
		}
	}

	public float MarkerDropper 
	{
		get {
			return array[7];
		}
		set {
			array[7]=value;
		}
	}

	public float HydrophoneFrequency 
	{
		get {
			return array[8];
		}
		set {
			array[8]=value;
		}
	}

	public override string ToString(){
		StringBuilder sb = new StringBuilder(256);
		// Without passing this class floats like "Infinity"
		// would be displayed in your system language.
        CultureInfo culture= CultureInfo.CreateSpecificCulture("en-US");

		
		sb.Append("longitudinal : ");
		sb.Append(array[0].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("lateral : ");
		sb.Append(array[1].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("vertical : ");
		sb.Append(array[2].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("yaw : ");
		sb.Append(array[3].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("camera : ");
		sb.Append(array[4].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("grabber : ");
		sb.Append(array[5].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("torpedo : ");
		sb.Append(array[6].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("marker dropper : ");
		sb.Append(array[7].ToString("0.##", culture));
		sb.Append("\n");
		
		sb.Append("hydrophone frequency : ");
		sb.Append(array[8].ToString("0.##", culture));
		sb.Append("\n");
		
		return sb.ToString();
	}
	const int length=9;
}
